### ISSUE TITLE
Fix the long description format for pypi

### ISSUE THREAD

**Issue by xmnlab** [heavyai/ibis-heavyai#44]
currently, https://pypi.org/project/ibis-omniscidb/ is using a wrong format for the long description.

**Comment by mikehinchey** [comment]
Also the ibis backend page for omnisci doesn’t exist: `[ibis-omniscidb](https://ibis-project.org/docs/backends/omnisci.html)`

**Comment by xmnlab** [comment]
this was already fixed.

@mikehinchey about your comment, not sure but I guess is that we should keep our documentation in our side. I can work on that.

**Comment by mikehinchey** [comment]
@xmnlab the readme in this repo (and thus in pypi) links to https://ibis-project.org/docs/backends/omnisci.html, which does not exist.

**Comment by tupui** [comment]
Should be fixed with rebranding. Closing this for now.
